[versions]
agp = "8.7.3"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.0"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
navigationFragmentKtx = "2.8.6"
navigationUiKtx = "2.8.6"
playServicesMaps = "19.0.0"
<<<<<<< HEAD
activity = "1.10.1"
<<<<<<< HEAD
firebaseAuthKtx = "23.2.0"
||||||| parent of 7be7a91 (feat/can_open_other_page)
=======
activity = "1.10.1"
>>>>>>> 7be7a91 (feat/can_open_other_page)
||||||| parent of e5ae47c (feat/login_ok)
=======
firebaseAuthKtx = "23.2.0"
>>>>>>> e5ae47c (feat/login_ok)

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
<<<<<<< HEAD
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
<<<<<<< HEAD
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
||||||| parent of 7be7a91 (feat/can_open_other_page)
=======
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
>>>>>>> 7be7a91 (feat/can_open_other_page)
||||||| parent of e5ae47c (feat/login_ok)
=======
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
>>>>>>> e5ae47c (feat/login_ok)

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

